# Generated by Django 2.0.6 on 2018-06-27 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('id_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link_http', models.URLField()),
                ('link_picture', models.URLField()),
                ('description', models.TextField()),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('saturated_fat_100g', models.FloatField()),
                ('carbohydrates_100g', models.FloatField()),
                ('energy_100g', models.FloatField(null=True)),
                ('sugars_100g', models.FloatField()),
                ('sodium_100g', models.FloatField()),
                ('categorie', models.ManyToManyField(related_name='products', to='food_and_search.Categorie')),
                ('user_product', models.ManyToManyField(blank=True, related_name='favourite_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
