# Generated by Django 2.0.5 on 2018-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('id_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link_http', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('nutrition_grade', models.CharField(max_length=1)),
                ('saturated_fat_100g', models.FloatField()),
                ('carbohydrates_100g', models.FloatField()),
                ('energy_100g', models.FloatField()),
                ('sugars_100g', models.FloatField()),
                ('sodium_100g', models.FloatField()),
                ('categories', models.ManyToManyField(to='food_and_search.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
