# Generated by Django 2.0.5 on 2018-05-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='carbohydrates_100g',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='energy_100g',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='saturated_fat_100g',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='sodium_100g',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='sugars_100g',
            field=models.SmallIntegerField(),
        ),
    ]
