# Generated by Django 2.0.6 on 2018-06-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_and_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sodium_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_100g',
            field=models.FloatField(null=True),
        ),
    ]
